remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins: ["jekyll-include-cache", "jekyll-feed"]

name: Gulg
title: Lux
title_separator: "-"
logo: /assets/images/lux.png

include: ["_pages"]

atom_feed:
  path: "/feed.xml"

defaults:
  # _docs
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      sidebar:
        nav: "pages"
