remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins: ["jekyll-include-cache", "jekyll-feed"]

name: Gulg
title: Lux
title_separator: "-"
logo: /assets/images/lux.png

atom_feed:
  path: "/feed.xml"
